config/routes.rb
Rails.application.routes.draw do
  # get 'bookings/new'
  # get 'bookings/edit'
  # get 'bookings/show'
  # get 'bookings/index'
  # get 'bouchtroues/index'
  # get 'bouchtroues/show'
  # get 'bouchtroues/new'
  # get 'bouchtroues/edit'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :bouchtroues do
    resources :bookings, only: [:new, :create, :index]
  end
  # http://127.0.0.1:3000/bouchtroues/new
resources :bookings, only: [:show, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bouchtroue

  validates :name, presence: true
  validates :date_start, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :event_time, presence: true
end

app/models/bouchtroue.rb
class Bouchtroue < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings


  validates :name_profile, presence: true
  validates :specialty, presence: true
  validates :description, presence: true
  # validates :rating, presence: true
  validates :status, presence: true
  validates :location, presence: true
  # validates :hour_price
  # validates :available_start
  # validates :available_end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bouchtroues
  has_many :bookings
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    @bouchtroue = @booking.bouchtroue
  end

  def index
  end

  def new
    @bouchtroue = Bouchtroue.find(params[:bouchtroue_id])
    @booking = Booking.new
  end

  def create
    @bouchtroue = Bouchtroue.find(params[:bouchtroue_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.bouchtroue = @bouchtroue
    @booking.save!
      if @booking.save
        redirect_to booking_path(@booking)
      else
        @bookings = @bouchtroue.bookings
       render "bouchtroues/show", status: :unprocessable_entity
      end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to root_path, status: :see_other
  end

  private


  def booking_params
    params.require(:booking).permit(:name, :description, :date_start, :location, :event_time)
  end
end

app/controllers/bouchtroues_controller.rb
class BouchtrouesController < ApplicationController
  before_action :set_bouchtroue, only: [:show, :edit, :update, :destroy]

  def index
    @bouchtroues = Bouchtroue.all
  end

  def show; end

  def new
    @bouchtroue = Bouchtroue.new
  end

  def create
    @bouchtroue = Bouchtroue.new(bouchtroue_params)
    @bouchtroue.user = current_user
    @bouchtroue.save!
    redirect_to bouchtroue_path(@bouchtroue)
  end

  def edit; end

  def update
    @bouchtroue.update!(bouchtroue_params)
    redirect_to bouchtroue_path(@bouchtroue)
  end

  def destroy
    @bouchtroue = Bouchtroue.find(params[:id])
    @bouchtroue.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_bouchtroue
    @bouchtroue = Bouchtroue.find(params[:id])
  end

  def bouchtroue_params
    params.require(:bouchtroue).permit(:name_profile, :specialty, :description, :status, :location, :available_start, :available_end, :hour_price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:home]
  def home
    @bouchtroues = Bouchtroue.all
    @bookings = Booking.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class = "container">

<h1 class = "container">Creer un profil de Bouchtroue</h1>

<%= simple_form_for ([@bouchtroue, @booking]) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :date_start %>
    <%= f.input :event_time %>
    <%= f.input :location %>
  </div>

  <div class="form-actions mb-5">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

</div>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<div class = "container">

<h1 class = "container">Création de votre reservation</h1>

<%= simple_form_for ([@bouchtroue, @booking]) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :date_start %>
    <%= f.input :event_time %>
    <%= f.input :location %>
  </div>

  <div class="form-actions mb-5">
    <%= f.button :submit, class: "btn" %>
  </div>
<% end %>

</div>

app/views/bookings/show.html.erb
<div class="container">
<h1>Votre reservation : <%= @booking.name %></h1>




  <div class ="d-flex">
    <p>Organisateur : <%= @booking.user.email %> et Victime : </p>
    <p>  <%= @booking.bouchtroue.name_profile %>@gmail.com</p>
  </div>

  <p>Description : <%= @booking.description %></p>
  <p>Lieux : <%= @booking.location %></p>


  <%= link_to "Home page", root_path, class: "btn btn-primary mt-2 mb-2 " %>
  <%= link_to "Modifier", edit_booking_path(@booking), class: "btn btn-primary mt-2 mb-2 " %>
  <%= link_to "Suppr", booking_path(@booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn flex-grow-1" %>
</div>

app/views/bouchtroues/edit.html.erb
<h1><%=  @bouchtroue.name_profile %></h1>


<%= simple_form_for @bouchtroue do |f| %>
  <div class="form-inputs">
    <%= f.input :name_profile %>
    <%= f.input :specialty %>
    <%= f.input :description %>
    <%= f.input :status %>
    <%= f.input :available_start %>
    <%= f.input :available_end %>
    <%= f.input :hour_price %>
    <%= f.input :location %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions mb-5">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bouchtroues/index.html.erb
<div class="fixed-top pt-5">
  <%= link_to "revenir", root_path, class: "btn btn-primary mt-2 mb-2" %>
</div>

<div class="container">
  <h1>Nos Bouchtrous disponibles</h1>
    <div class="index-grid">
      <% @bouchtroues.each do |bouchtroue| %>
        <% if bouchtroue.user.email != current_user.email %>
          <div class="card">
            <div class="d-flex justify-content-center align-items-center img-fluid w-auto h-auto">
              <%= cl_image_tag bouchtroue.photo.key, width: 180,lenght: 190, class: "pdpd" %>
            </div>
            <div class="card-info">
              <p class="text-title m-1"><%= bouchtroue.name_profile %></p>
              <p class= "m-1">Rating 8.5</p>
              <p class="text-body m-1">Spécialité : <%= bouchtroue.specialty %></p>
              <% if bouchtroue.status == "libre" %>
                <%= link_to "en savoir plus", bouchtroue_path(bouchtroue), class: "btn-grad" %>
              <% elsif bouchtroue.status == "occupe" %>
                <%= link_to "en savoir plus", bouchtroue_path(bouchtroue), class: "btn-grad" %>
              <% else %>
                <%= link_to "en savoir plus", bouchtroue_path(bouchtroue), class: "btn-grad" %>
              <% end %>
            <div class="card-footer d-flex justify-content-end">
              <span class="text-title"><%= bouchtroue.hour_price %> € ttc</span>

            </div>
          </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>
</div>

app/views/bouchtroues/new.html.erb
<div class = "container">

<h1 class = "container">Creer un profil de Bouchtroue</h1>

<%= simple_form_for @bouchtroue do |f| %>
  <div class="form-inputs">
    <%= f.input :name_profile %>
    <%= f.input :specialty %>
    <%= f.input :description %>
    <%= f.input :status %>
    <%= f.input :location %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions mb-5">
    <%= f.button :submit, class: "btn" %>
  </div>
<% end %>

</div>

app/views/bouchtroues/show.html.erb
<div class = "fixed-top pt-5">
<% if @bouchtroue.user.email == current_user.email %>
  <%= link_to "revenir", root_path, class: "btn btn-primary mt-2 mb-2 " %>
<% else %>
  <%= link_to "revenir", bouchtroues_path, class: "btn btn-primary mt-2 mb-2 " %>
<% end %>
</div>

<div class="container">
  <div class="text-center">
    <h1>Mon profil : <%= @bouchtroue.name_profile %></h1>
  </div>
    <br>
    <div class="row">
      <div class="col-md-4">
        <%= cl_image_tag @bouchtroue.photo.key, width: 180,lenght: 190, class: "pdp" %>
      </div>
      <div class="col-md-8">
        <div class="row">
          <p>Spécialité : <%= @bouchtroue.specialty %></p>
          <p>Description : <%= @bouchtroue.description %></p>
          <p>Status : <%= @bouchtroue.status %>.</p>
          <p> Mes dispo du moment : <%= @bouchtroue.available_start %> au <%= @bouchtroue.available_end %></p>
          <p> Rating : </p>
          <p>Prix : <%= @bouchtroue.hour_price %> € / heure</p>
          <p>Localisation du moment : <%= @bouchtroue.location %></p>
        </div>
        <div class="row col-md-2">
          <% if @bouchtroue.user.email == current_user.email %>
          <div class = "d-flex m-2">
            <div class = "m-2"><%= link_to "edit", edit_bouchtroue_path(@bouchtroue), class: "btn" %></div>
            <div class = "m-2"><%= link_to "Suppr", bouchtroue_path(@bouchtroue), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn flex-grow-1" %></div>
          </div>
          <% else %>
          <% end %>
          <% if @bouchtroue.user.email != current_user.email %>
            <%= link_to "reserver", new_bouchtroue_booking_path(@bouchtroue), class: "btn" %>
          <% else %>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bouchtrou</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
       <%= render "shared/navbar" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
  <h1>Si tu n'as pas d'amis, tu es au bon endroit !</h1>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-12 col-lg-6">
      <br>
      <%= link_to "Trouver un bouchtrou", bouchtroues_path, class: "btn", id: "trouver-btn" %>
      <%= link_to "Ajouter un bouchtrou", new_bouchtroue_path, class: "btn", id: "ajouter-btn" %>
    </div>
  </div>


  <div id="my-profile" class ="mt-5">
  <h2>Mes profils</h2>
    <div class="row">
      <% @bouchtroues.each do |bouchtroue| %>
        <% if bouchtroue.user.email == current_user.email %>
          <div class = "d-flex justify-content-around col-4">
            <div class="container py-2 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                  <div class="card w-100 h-100" style="border-radius: 15px;">
                    <div class="card-body p-4">

                      <div class="d-flex text-black">
                        <div class="flex-shrink-0">
                          <%= cl_image_tag bouchtroue.photo.key, width: 180, crop: :fill %>
                        </div>

                        <div class="flex-grow-1 ms-3">
                          <h5 class="mb-1"><%= bouchtroue.name_profile %></h5>
                          <p class="mb-2 pb-1" style="color: #2b2a2a;"><%= bouchtroue.specialty %></p>
                          <div class="d-flex justify-content-start rounded-3 p-2 mb-2"
                            style="">
                            <div>
                            <% if bouchtroue.status != "occupe" %>
                              <h5>Disponibilités</h5>
                              <p class="small text-muted mb-1"><%= bouchtroue.available_start %></p>
                              <p class="small text-muted mb-1"><%= bouchtroue.available_end %></p>
                              <p>Sur : <%= bouchtroue.location %></p>
                            <% else %>
                              <h5>Indisponible</h5>
                              <p> Le profil se mettra a jour automatiquement</p>
                              <p> </p>
                              <p> </p>
                            <% end %>

                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="d-flex pt-1">
                      <%= link_to "Profil", bouchtroue_path(bouchtroue), class: "btn me-1 flex-grow-1" %>
                      <%= link_to "Modifier", edit_bouchtroue_path(bouchtroue), class: "btn me-1 flex-grow-1" %>
                      <%# attention modif bug %>
                      <%= link_to "Suppr", bouchtroue_path(bouchtroue), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn flex-grow-1" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% else %>
        <% end %>
      <% end %>
    </div>
  </div>


<%# if booking.user.email == current_user.email or %>
<%# @bouchtrou.user.email %>

  <div id="my-profile" class ="mt-5">
    <h2>Mes reservations</h2>
  </div>

<div class="row">
  <% @bookings.each do |booking| %>
    <% if booking.user.email == current_user.email || current_user.id == booking.bouchtroue.user_id %>
        <div class = "my-2 ml-0 d-flex justify-content-around col-4">
          <div class="card w-100 h-100" style="border-radius: 15px;">
            <div class="card-body">
              <div class="col">
                  <h5><%= booking.name %></h5>
                    <p>Description : <%= booking.description %></p>
                    <p>Date : <%= booking.date_start %></p>
                    <p>Lieu : <%= booking.location %></p>
                    <p>Pour une durée de <%= booking.event_time %> h</p>
              </div>
            </div>
            <div class="d-flex pt-1">
              <%= link_to "Modifier", edit_booking_path(booking), class: "btn me-1 flex-grow-1" %>
              <%# attention modif bug %>
              <%= link_to "Suppr", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn flex-grow-1" %>
            </div>
          </div>
        </div>
    <% else %>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag("nofriends.jpg") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar" viewBox="0 0 16 16">
  <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
</svg>

  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="search-form-control form-group d-flex">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" />
      <button name="button" type="submit" class="fas fa-search">
      </button>
    </div>
  <% end %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <button class="conv">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#0D0630" class="bi bi-chat" viewBox="0 0 16 16">
                <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
              </svg>
            </button>

            <button class="star">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#F8D65B" class="bi bi-star" viewBox="0 0 16 16">
                <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
              </svg>
            </button>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>